<?xml version="1.0"?>
<package format="2">
  <name>cam_lidar_planner_ros</name>
  <version>1.0.0</version>
  <description>The cam_lidar_planner_ros package</description>

  
  <maintainer email="cezary.naworski98@gmail.com">czarek</maintainer>

  <!-- One license tag required, multiple allowed, one license per tag -->
  <!-- Commonly used license strings: -->
  <!--   BSD, MIT, Boost Software License, GPLv2, GPLv3, LGPLv2.1, LGPLv3 -->
  <license>MIT</license>
  <buildtool_depend>catkin</buildtool_depend>

  <depend>roscpp</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>image_transport</depend>

  <build_depend>pcl_conversions</build_depend>
  <build_depend>pcl_ros</build_depend>

   <build_export_depend>pcl_conversions</build_export_depend>
  <build_export_depend>pcl_ros</build_export_depend>
   <build_depend>libpcl-all-dev</build_depend>


  <!-- The export tag contains other, unspecified, tags -->
  <export>
    <!-- Other tools can request additional information be placed here -->

  </export>
</package>
